### PR TITLE
update doc 206

### PR DESCRIPTION
**Pull request by yangtaogit**

### CODE REVIEW

**Comment by xshi** [comment]
@liukaihep Could you review this one? Thanks!

**Comment by liukaihep** [comment]
Here are some comments
- add reference of the figure.
- add capital of the figure. it is the displacement damage cross section normalized to 95 MeV mb
- Here are some suggestions on the first paragraph.
    -  suggest to add an introduction of the basic physics picture.  The total energy loss including some different types, the NIEL only describes the part of displacement damage,  the other energy loss, such as ionization not included.
    -   "different particles with different energie" may be not clear enough,  try different particles or particles with different energy.
    -  It would be confusing by adding that figure just below "regardless of particle energy and type".     Actually,  on the plot, the displacement damage cross section (**D**) is depending on the particle type and energy.   My understanding, the key point of the NIEL assumption is, the displacement damage caused by different particles/ particles with different energies **could be scaled via the NIEL**, hence we could  normalize the value from one particle to another, or from one energy to another for the same type particle.  meaning of the **normalize**  may be different from **regardless**.
- the variables appears in the figure and formula, should be explained, especially **D**, the displacement damage cross section.

**Comment by yangtaogit** [comment]
the modified version is pushed on git.

**Comment by liukaihep** [comment]
Dear @xshi @yangtaogit 
I am OK with the latest version.
It could be merged if no further comments from you.

**Pull request merged**
