### PR TITLE
update for silicon detector

### PR DESCRIPTION
**Pull request by xiaosy1**

### CODE REVIEW

**Comment by xshi** [comment]
@rkiuchi Could you review this?

**Comment by rkiuchi** [comment]
Hi, since general/outline of semi-conductor is described, here are some comments with that respect:  

* "It is located in group IV of the periodic table of elements and compound semiconductor materials",     
I wonder that despite Si/Ge are major elements (and compound of them), we can pick-up III-V GaAs,  and just another different type of example 
 is Fullerene from these days research.     
Probably, above sentence "It is located ..."  might include those examples,   but could you list/add more examples ?     
 
* At the end (or beginning?) of explanation of PN junction, could you also mention about the Schottky barrier junction  
as another type of junction ?

**Comment by xiaosy1** [comment]
> Hi, since general/outline of semi-conductor is described, here are some comments with that respect:
> 
>     * "It is located in group IV of the periodic table of elements and compound semiconductor materials",
>       I wonder that despite Si/Ge are major elements (and compound of them), we can pick-up III-V GaAs,  and just another different type of example
>       is Fullerene from these days research.
>       Probably, above sentence "It is located ..."  might include those examples,   but could you list/add more examples ?
> 
>     * At the end (or beginning?) of explanation of PN junction, could you also mention about the Schottky barrier junction
>       as another type of junction ?

Thank you very much for your comments. 
And new version has been updated accordingly.

**Comment by rkiuchi** [comment]
Thank you so much ! I have confirmed this updates.

**Comment by xshi** [comment]
https://xiaosy1.github.io/docs/202_silicon/

the equation is not showing up properly.

**Pull request merged**
