### PR TITLE
303 VSCode and 203 pixel updated

### PR DESCRIPTION
**Pull request by Zombatar**

### CODE REVIEW

**Comment by xshi** [comment]
@rkiuchi  Could you please review the 203? Thanks!

**Comment by rkiuchi** [comment]
Following is some comments related to "203_pixel.md"  
   
* As a notation,  "fixed charge"  would be better to "space charge"    
* For the list 3,   "Calculate the negative gradient of ... which is called Weighting Poential ..." would be Wighting Filed.   

More general,     
the contents explain how to obtain the induced current from the theorem
rather than the introduction of theorem itself though it is partially introduced,
I would prefer to separate description a bit more,     
the explanation(introduction) of theorem & steps to calculate the induced current.     

Such as:  

* Equation of theorem, together with definition of variable, e.g. weighting potential
* Assumption , e.g. electric dynamics (it is already described), field propagates instantaneously, ,,, super position of fields ?        
   
and then, the actual calculation steps of the induced current as already provided.

**Comment by rkiuchi** [comment]
P.S.  

the velocity calculation part is I am not clear, I mean, I do not have solid ideas/knowledges.  
I feel,  for example,     
1. E-field is obtained via a calculation 2.  from the measurement of induced current, obtain the velocity    
--> if that is the case,  the logic, we can calculate the induced current from E-filed & velocity is a bit strange.
2. Normally, we can assume/measure the mobility (=velocity) by the other methods,  which gives us estimation of 
induced current.

**Comment by rkiuchi** [comment]
Hi @Zombatar 

Since we have to make a balance of, such as the content amount with the others,  i.e. doc 201 by @rkiuchi,
I would prefer to update the words, then it is ready to be merged.
  
* As a notation, "fixed charge" would be better to "space charge"
* For the list 3, "Calculate the negative gradient of ... which is called Weighting Poential ..." would be Wighting Filed.

**Comment by Zombatar** [comment]
> Hi @Zombatar
> 
> Since we have to make a balance of, such as the content amount with other document, i.e. doc 201 by @rkiuchi,
> I would prefer to update the words, then it is ready to be merged.
> 
> * As a notation, "fixed charge" would be better to "space charge"
> * For the list 3, "Calculate the negative gradient of ... which is called Weighting Poential ..." would be Wighting Filed.

done

**Comment by rkiuchi** [comment]
Thanks !

**Comment by Zombatar** [comment]
> P.S.
> 
> the velocity calculation part is I am not clear, I mean, I do not have solid ideas/knowledges.
> I feel, for example,
> 
> 1. E-field is obtained via a calculation 2.  from the measurement of induced current, obtain the velocity
>    --> if that is the case,  the logic, we can calculate the induced current from E-filed & velocity is, as the explanation step,  a bit strange.
> 2. Normally, we can assume/measure the mobility (=velocity) by the other methods,  which gives us estimation of
>    induced current.

Actually，I think because of the huge number of carriers and the velocity is a vector,  we can not make it that from the measurement of induced current, obtain the velocity.

**Pull request merged**
